import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { rxova } from "@rxova/repo-config/eslint";

const PACKAGE_BOUNDARY_FILE_GLOBS = [
  "packages/*/src/**/*.{ts,tsx,mts,cts}",
  "packages/*/test/**/*.{ts,tsx,mts,cts}",
];
const REPO_ROOT = path.dirname(fileURLToPath(import.meta.url));
const PACKAGES_ROOT = path.join(REPO_ROOT, "packages");
const WORKSPACE_PACKAGES = fs
  .readdirSync(PACKAGES_ROOT, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => {
    const packageDir = path.join(PACKAGES_ROOT, entry.name);
    const packageJson = JSON.parse(fs.readFileSync(path.join(packageDir, "package.json"), "utf8"));
    const declaredWorkspaceDependencies = new Set(
      [
        ...Object.keys(packageJson.dependencies ?? {}),
        ...Object.keys(packageJson.devDependencies ?? {}),
        ...Object.keys(packageJson.peerDependencies ?? {}),
        ...Object.keys(packageJson.optionalDependencies ?? {}),
      ].filter((dependencyName) => dependencyName.startsWith("@rxova/")),
    );

    return {
      dir: packageDir,
      dirName: entry.name,
      name: packageJson.name,
      declaredWorkspaceDependencies,
    };
  });

function findWorkspacePackageForFile(filePath) {
  return WORKSPACE_PACKAGES.find(
    (workspacePackage) =>
      filePath === workspacePackage.dir ||
      filePath.startsWith(`${workspacePackage.dir}${path.sep}`),
  );
}

function findWorkspacePackageForImport(specifier) {
  return WORKSPACE_PACKAGES.find(
    (workspacePackage) =>
      specifier === workspacePackage.name || specifier.startsWith(`${workspacePackage.name}/`),
  );
}

const workspacePlugin = {
  rules: {
    "enforce-package-boundaries": {
      meta: {
        type: "problem",
        docs: {
          description:
            "Require internal workspace packages to be imported via their package name and only when declared.",
        },
        schema: [],
      },
      create(context) {
        const filename = context.filename ?? context.getFilename();

        if (!path.isAbsolute(filename)) {
          return {};
        }

        const sourcePackage = findWorkspacePackageForFile(filename);

        if (!sourcePackage) {
          return {};
        }

        function checkImport(node, sourceNode) {
          const specifier = sourceNode?.value;

          if (typeof specifier !== "string") {
            return;
          }

          if (specifier.startsWith(".")) {
            const resolvedPath = path.resolve(path.dirname(filename), specifier);
            const targetPackage = findWorkspacePackageForFile(resolvedPath);

            if (targetPackage && targetPackage.name !== sourcePackage.name) {
              context.report({
                node: sourceNode,
                message: `Import from ${targetPackage.name} via its package name instead of a relative path.`,
              });
            }

            return;
          }

          const targetPackage = findWorkspacePackageForImport(specifier);

          if (!targetPackage || targetPackage.name === sourcePackage.name) {
            return;
          }

          if (!sourcePackage.declaredWorkspaceDependencies.has(targetPackage.name)) {
            context.report({
              node: sourceNode,
              message: `Declare ${targetPackage.name} in packages/${sourcePackage.dirName}/package.json before importing it.`,
            });
          }
        }

        return {
          ExportAllDeclaration(node) {
            checkImport(node, node.source);
          },
          ExportNamedDeclaration(node) {
            if (node.source) {
              checkImport(node, node.source);
            }
          },
          ImportDeclaration(node) {
            checkImport(node, node.source);
          },
          ImportExpression(node) {
            checkImport(node, node.source);
          },
          TSImportType(node) {
            checkImport(node, node.argument);
          },
        };
      },
    },
  },
};

export default rxova(
  {
    tsconfigRootDir: import.meta.dirname,
    // The libraries run in browsers and on Node; the extension talks to `chrome`.
    node: true,
    browser: true,
    tests: {
      files: [
        "test/**",
        "**/test/**",
        "**/__tests__/**",
        "**/*.{test,spec}.{ts,tsx,js,jsx,mts,cts,cjs}",
      ],
    },
    // Hooks live in `.ts` files as well as `.tsx` (use-journey.ts), so the React
    // layer covers both. `useIsomorphicLayoutEffect` (from @rxova/ts-utils) is
    // `useLayoutEffect` on the client and `useEffect` on the server; without
    // naming it here its dependency arrays are invisible to exhaustive-deps,
    // which is most of the effects in packages/react.
    react: {
      files: ["**/*.{ts,tsx}"],
      additionalHooks: "(useIsomorphicLayoutEffect)",
    },
    ignores: [
      "worktrees/",
      "flow/",
      "**/.next/",
      "**/*.d.ts",
      // Generated by TypeDoc in the docs `prebuild` hook.
      "apps/docs/src/content/docs/*/api/reference/",
    ],
    // Build scripts, the repository's scripts and the docs tooling print to
    // stdout by design. The development-warning helpers and the core's listener
    // error reporter exist to write to the console, and the examples log what
    // the journey does so a reader can watch it happen.
    consoleAllowed: [
      "scripts/**",
      "packages/*/scripts/**",
      "apps/*/scripts/**",
      "packages/*/src/internal/dev.ts",
      "packages/core/src/core/helpers.ts",
      "examples/**",
    ],
    rules: {
      // A setState in an effect is how the devtools panel and the examples sync
      // with an external source; the rule's suggested rewrites do not apply.
      "react-hooks/set-state-in-effect": "off",
      // Forwarding a rejection reason as received is how the runtime relays a
      // failed step handler: wrapping it in an Error would change what callers
      // catch.
      "@typescript-eslint/prefer-promise-reject-errors": [
        "error",
        { allowThrowingAny: true, allowThrowingUnknown: true },
      ],
    },
  },
  {
    // The Chrome extension APIs, on every file of the extension and its tests.
    files: ["apps/devtools/**"],
    languageOptions: { globals: { chrome: "readonly" } },
  },
  {
    // Journey's own house rules, on every file the preset lints.
    rules: {
      "no-nested-ternary": "error",
    },
  },
  {
    files: ["**/*.mjs"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "Program",
          message: "Use .ts or .js files. .mjs is not allowed in this repository.",
        },
      ],
    },
  },
  {
    // Workspace packages import each other by package name, and only once the
    // dependency is declared: a relative import across packages works in the
    // monorepo and breaks in the published tarball.
    files: PACKAGE_BOUNDARY_FILE_GLOBS,
    plugins: {
      workspace: workspacePlugin,
    },
    rules: {
      "workspace/enforce-package-boundaries": "error",
    },
  },
  {
    // Colocated tests must exercise the public entrypoints: import via the
    // package name (or its internal /testing alias), never by reaching into
    // src with parent-relative paths. Sibling imports (./fixtures) stay legal.
    files: [
      "packages/*/src/**/__tests__/**/*.{ts,tsx,mts,cts}",
      "apps/*/src/**/__tests__/**/*.{ts,tsx,mts,cts}",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["../**"],
              message:
                "Import via the package name (@rxova/…) instead of a parent-relative path; use the package's /testing alias for shared test helpers.",
            },
          ],
        },
      ],
    },
  },
);
