import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const defaultRepoRoot = path.resolve(__dirname, "../../..");
const REPO_BLOB_BASE_URL = "https://github.com/rxova/journey/blob/main";

type LogFn = (message: string) => void;
type ErrorFn = (message: string) => void;
type ExitFn = (code: number) => void;

export type ReleaseNoteSource = {
  source: string;
  target: string;
  title: string;
  description: string;
};

export type SyncReleaseNotesOptions = {
  repoRoot?: string;
  sources?: readonly ReleaseNoteSource[];
  log?: LogFn;
};

export type CheckReleaseNotesOptions = {
  repoRoot?: string;
  sources?: readonly ReleaseNoteSource[];
  log?: LogFn;
  error?: ErrorFn;
  exit?: ExitFn;
};

export type MainOptions = {
  argv?: string[];
  repoRoot?: string;
  sources?: readonly ReleaseNoteSource[];
  log?: LogFn;
  error?: ErrorFn;
  exit?: ExitFn;
};

export type SyncReleaseNotesResult = {
  updated: string[];
};

export type CheckReleaseNotesResult = {
  stale: string[];
};

export type MainResult = {
  updated?: string[];
  stale?: string[];
};

const defaultExit: ExitFn = (code) => {
  process.exit(code);
};

export const releaseNoteSources: readonly ReleaseNoteSource[] = [
  {
    source: "packages/core/CHANGELOG.md",
    target: "apps/docs/docs/core/releases.md",
    title: "Core Releases",
    description: "Release notes sourced from the Core package changelog (Changesets)."
  },
  {
    source: "packages/react/CHANGELOG.md",
    target: "apps/docs/docs/react/releases.md",
    title: "React Releases",
    description: "Release notes sourced from the React package changelog (Changesets)."
  },
  {
    source: "packages/devtools-bridge/CHANGELOG.md",
    target: "apps/docs/docs/bridge/releases.md",
    title: "Bridge Releases",
    description: "Release notes sourced from the Devtools Bridge package changelog (Changesets)."
  },
  {
    source: "apps/devtools/CHANGELOG.md",
    target: "apps/docs/docs/devtool/releases.md",
    title: "Chrome DevTools Releases",
    description:
      "Release notes sourced from the Chrome DevTools app changelog (outside package Changesets)."
  }
];

export const toRepoPath = (repoRoot: string, ...parts: string[]): string => {
  return path.join(repoRoot, ...parts);
};

export const readUtf8 = (filePath: string): string => {
  return readFileSync(filePath, "utf8").replace(/\r\n/g, "\n");
};

export const escapeMdxInlineGenerics = (text: string): string => {
  const segments = text.split("`");
  for (let index = 0; index < segments.length; index += 2) {
    const segment = segments[index];
    if (!segment) {
      continue;
    }
    segments[index] = segment.replace(/\b([A-Za-z_$][\w$.]*<[^<>\n]+>)/g, "`$1`");
  }
  return segments.join("`");
};

export const normalizeChangelog = (markdown: string): string => {
  const lines = markdown.split("\n");
  const firstLine = lines[0] ?? "";
  const withoutTopHeading = /^#\s+/.test(firstLine) ? lines.slice(1) : lines;

  while (withoutTopHeading.length > 0 && withoutTopHeading[0]?.trim() === "") {
    withoutTopHeading.shift();
  }

  const normalized = `${withoutTopHeading.join("\n").trimEnd()}\n`;
  return escapeMdxInlineGenerics(normalized);
};

export const renderReleaseDoc = (entry: ReleaseNoteSource | undefined, body: string): string => {
  if (!entry) {
    throw new Error("Missing release note source entry.");
  }
  const sourceUrl = `${REPO_BLOB_BASE_URL}/${entry.source}`;
  return `---
title: ${entry.title}
sidebar_label: Releases
---

<!-- AUTO-GENERATED by packages/common/tooling/sync-doc-release-notes.ts. Do not edit manually. -->

${entry.description}

Source: [\`${entry.source}\`](${sourceUrl})

${body}`;
};

export const expectedContent = (
  entry: ReleaseNoteSource | undefined,
  repoRoot = defaultRepoRoot
): string => {
  if (!entry) {
    throw new Error("Missing release note source entry.");
  }
  const sourcePath = toRepoPath(repoRoot, entry.source);
  const changelog = readUtf8(sourcePath);
  const normalizedBody = normalizeChangelog(changelog);
  return renderReleaseDoc(entry, normalizedBody);
};

export const writeIfChanged = (filePath: string, content: string): boolean => {
  let current = "";
  try {
    current = readUtf8(filePath);
  } catch {
    // File does not exist yet.
  }

  if (current === content) {
    return false;
  }

  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, content, "utf8");
  return true;
};

export const checkMatches = (filePath: string, content: string): boolean => {
  let current: string;
  try {
    current = readUtf8(filePath);
  } catch {
    return false;
  }
  return current === content;
};

export const syncReleaseNotes = ({
  repoRoot = defaultRepoRoot,
  sources = releaseNoteSources,
  log = console.log
}: SyncReleaseNotesOptions = {}): SyncReleaseNotesResult => {
  const updated: string[] = [];

  for (const entry of sources) {
    const targetPath = toRepoPath(repoRoot, entry.target);
    const content = expectedContent(entry, repoRoot);
    if (writeIfChanged(targetPath, content)) {
      updated.push(entry.target);
    }
  }

  if (updated.length === 0) {
    log("Release note docs are already up to date.");
    return { updated };
  }

  for (const file of updated) {
    log(`Updated ${file}`);
  }

  return { updated };
};

export const checkReleaseNotes = ({
  repoRoot = defaultRepoRoot,
  sources = releaseNoteSources,
  log = console.log,
  error = console.error,
  exit = defaultExit
}: CheckReleaseNotesOptions = {}): CheckReleaseNotesResult => {
  const stale: string[] = [];

  for (const entry of sources) {
    const targetPath = toRepoPath(repoRoot, entry.target);
    const content = expectedContent(entry, repoRoot);
    if (!checkMatches(targetPath, content)) {
      stale.push(entry.target);
    }
  }

  if (stale.length > 0) {
    error("Release note docs are out of date. Run: pnpm run docs:release-notes:sync");
    for (const file of stale) {
      error(`- ${file}`);
    }
    exit(1);
    return { stale };
  }

  log("Release note docs are up to date.");
  return { stale };
};

export const main = ({
  argv = process.argv,
  repoRoot = defaultRepoRoot,
  sources = releaseNoteSources,
  log = console.log,
  error = console.error,
  exit = defaultExit
}: MainOptions = {}): MainResult => {
  if (argv.includes("--check")) {
    return checkReleaseNotes({ repoRoot, sources, log, error, exit });
  }

  return syncReleaseNotes({ repoRoot, sources, log });
};

export const isEntrypoint = (
  entryArg: string | undefined = process.argv[1],
  moduleUrl: string = import.meta.url
): boolean => {
  if (!entryArg) return false;
  return pathToFileURL(entryArg).href === moduleUrl;
};

/* c8 ignore next 3 */
if (isEntrypoint()) {
  main();
}
