import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  bridgeSidebar: [
    {
      type: "category",
      label: "Learn",
      collapsed: false,
      items: ["getting-started"]
    },
    {
      type: "category",
      label: "Use it",
      collapsed: false,
      items: ["bridge-api", "examples"]
    },
    {
      type: "category",
      label: "Reference",
      collapsed: true,
      items: ["protocol", "releases"]
    },
    {
      // Auto-generated TypeDoc output, sourced from the per-kind subfolders (not
      // the dir root) so the generated README index page is not pulled in as a
      // stray sidebar item — the category is a pure collapsible container.
      type: "category",
      label: "API reference",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Functions",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/reference/functions" }]
        },
        {
          type: "category",
          label: "Type aliases",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/reference/type-aliases" }]
        },
        {
          type: "category",
          label: "Variables",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/reference/variables" }]
        }
      ]
    }
  ]
};

export default sidebars;
