import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  coreSidebar: [
    {
      type: "category",
      label: "Learn",
      collapsed: false,
      items: ["overview", "getting-started", "concepts"]
    },
    {
      type: "category",
      label: "Use it",
      collapsed: false,
      items: ["usage/linear", "usage/graph", "usage/headless", "effects", "recipes", "examples"]
    },
    {
      type: "category",
      label: "Understand it",
      collapsed: true,
      items: ["architecture", "snapshot", "lifecycle", "async", "history"]
    },
    {
      type: "category",
      label: "Extend it",
      collapsed: true,
      items: [
        "plugins/overview",
        "plugins/authoring",
        "persistence",
        "autosave",
        "plugins/analytics-plugin",
        "plugins/replay-plugin",
        "plugins/diagnostics-plugin",
        "plugins/execution-paths-plugin"
      ]
    },
    {
      type: "category",
      label: "Reference",
      collapsed: true,
      items: [
        "api/overview",
        "api/transitions-syntax",
        "api/graph-builder",
        "typescript",
        "comparison",
        "coming-from-xstate",
        "stability",
        "pre-1-0-migration",
        "faq",
        "releases"
      ]
    },
    {
      // Auto-generated TypeDoc output. Kept as its own top-level section, and
      // sourced from the per-kind subfolders (not the dir root) so the generated
      // README index page is not pulled in as a stray, navigating sidebar item —
      // the category is a pure collapsible container.
      type: "category",
      label: "API reference",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Classes",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/reference/classes" }]
        },
        {
          type: "category",
          label: "Functions",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/reference/functions" }]
        },
        {
          type: "category",
          label: "Type aliases",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/reference/type-aliases" }]
        }
      ]
    }
  ]
};

export default sidebars;
