import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  coreSidebar: [
    {
      type: "category",
      label: "Learn",
      collapsed: false,
      items: ["overview", "getting-started", "concepts"]
    },
    {
      type: "category",
      label: "Use it",
      collapsed: false,
      link: { type: "doc", id: "usage/index" },
      items: ["usage/linear", "usage/graph", "usage/headless", "recipes", "examples"]
    },
    {
      type: "category",
      label: "Understand it",
      collapsed: true,
      items: ["architecture", "snapshot", "lifecycle", "async", "history"]
    },
    {
      type: "category",
      label: "Extend it",
      collapsed: true,
      items: [
        "plugins/overview",
        "plugins/authoring",
        "persistence",
        "autosave",
        "plugins/analytics-plugin",
        "plugins/replay-plugin",
        "plugins/diagnostics-plugin",
        "plugins/execution-paths-plugin"
      ]
    },
    {
      type: "category",
      label: "Reference",
      collapsed: true,
      items: [
        "api/overview",
        "api/transitions-syntax",
        "api/graph-builder",
        {
          type: "category",
          label: "API reference",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/reference" }]
        },
        "typescript",
        "comparison",
        "stability",
        "pre-1-0-migration",
        "faq",
        "releases"
      ]
    }
  ]
};

export default sidebars;
