import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  coreSidebar: [
    "getting-started",
    {
      type: "category",
      label: "Overview",
      collapsed: true,
      items: ["overview", "stability", "pre-1-0-migration"]
    },
    {
      type: "category",
      label: "Usage",
      collapsed: true,
      link: { type: "doc", id: "usage/index" },
      items: ["usage/linear", "usage/graph", "usage/headless"]
    },
    "typescript",
    {
      type: "category",
      label: "API",
      collapsed: true,
      items: [
        "api/overview",
        "api/transitions-syntax",
        "api/graph-builder",
        {
          type: "category",
          label: "Reference",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "api/reference" }]
        }
      ]
    },
    {
      type: "category",
      label: "Plugins",
      collapsed: true,
      items: [
        "plugins/overview",
        "plugins/authoring",
        "persistence",
        "autosave",
        "plugins/analytics-plugin",
        "plugins/replay-plugin",
        "plugins/diagnostics-plugin",
        "plugins/execution-paths-plugin"
      ]
    },
    {
      type: "category",
      label: "Machine Architecture",
      collapsed: true,
      items: [
        "architecture",
        "architecture/create-journey-machine",
        "architecture/journey-definition-resolver",
        "architecture/plugin-controller",
        "architecture/runtime",
        "architecture/async-state",
        "architecture/navigation",
        "architecture/send",
        "architecture/controls",
        "architecture/helpers"
      ]
    },
    {
      type: "category",
      label: "Runtime Reference",
      collapsed: true,
      items: ["runtime-reference", "snapshot", "lifecycle", "async", "history"]
    },
    "recipes",
    "examples",
    "comparison",
    "faq",
    "releases"
  ]
};

export default sidebars;
