import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  reactSidebar: [
    {
      type: "category",
      label: "Learn",
      collapsed: false,
      items: ["overview", "quickstart"]
    },
    {
      type: "category",
      label: "Use it",
      collapsed: false,
      items: ["provider-and-hooks", "async-ui", "patterns", "examples"]
    },
    {
      type: "category",
      label: "Reference",
      collapsed: true,
      items: ["typescript", "devtools", "releases"]
    },
    {
      type: "category",
      label: "API reference",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "api/reference" }]
    }
  ]
};

export default sidebars;
