import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  reactSidebar: [
    "overview",
    "quickstart",
    "provider-and-hooks",
    "patterns",
    "async-ui",
    "devtools",
    "examples",
    "typescript",
    "releases",
    {
      type: "category",
      label: "API Reference",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "api/reference" }]
    }
  ]
};

export default sidebars;
